In [2]:
import pandas as pd
import numpy as np

In [3]:
df2021 = pd.read_csv("tn_2021_results.csv")
df2026 = pd.read_csv("tn_2026_results.csv")
master = pd.read_csv("constituency_master.csv")

In [7]:
df2021.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro
1,Gummidipundi,1,PRAKASH M,PMK,75514,78.08,GEN,Chennai Metro
2,Gummidipundi,1,USHA,NTK,11701,78.08,GEN,Chennai Metro
3,Gummidipundi,1,DILLIY K.M,DMDK,2576,78.08,GEN,Chennai Metro
4,Gummidipundi,1,None Of The Above,NOTA,1783,78.08,GEN,Chennai Metro

In [8]:
df2026.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro
1,Gummidipoondi,1,SUDHAKAR.V,AIADMK,66375,NaN,GEN,Chennai Metro
2,Gummidipoondi,1,T.J.GOVINDARAJAN,DMK,62492,NaN,GEN,Chennai Metro
3,Gummidipoondi,1,"R.SRIDAR. B.L.,",NTK,4756,NaN,GEN,Chennai Metro
4,Gummidipoondi,1,NOTA,NOTA,937,NaN,GEN,Chennai Metro

In [9]:
master.head()

   ac_number  constituency    district         region reserved
0          1  Gummidipundi  Tiruvallur  Chennai Metro      GEN
1          2       Ponneri  Tiruvallur  Chennai Metro       SC
2          3     Tiruttani  Tiruvallur  Chennai Metro      GEN
3          4   Thiruvallur  Tiruvallur  Chennai Metro      GEN
4          5   Poonamallee  Tiruvallur  Chennai Metro       SC

In [10]:
df2021.info()

<class 'pandas.DataFrame'>
RangeIndex: 4232 entries, 0 to 4231
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   constituency  4232 non-null   str
 1   ac_number     4232 non-null   int64
 2   candidate     4232 non-null   str
 3   party         4232 non-null   str
 4   votes         4232 non-null   int64
 5   turnout       4232 non-null   float64
 6   reserved      4232 non-null   str
 7   region        4232 non-null   str
dtypes: float64(1), int64(2), str(5)
memory usage: 264.6 KB

In [12]:
winner2021 = df2021.loc[df2021.groupby('ac_number')['votes'].idxmax()]
winner2026 = df2026.loc[df2026.groupby('ac_number')['votes'].idxmax()]

In [13]:
winner2021.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro
13,Ponneri,2,DURAI. CHANDRASEKAR,INC,94528,78.20,SC,Chennai Metro
24,Tiruttani,3,S.Chandran,DMK,120314,78.76,GEN,Chennai Metro
39,Thiruvallur,4,"RAAJENDRAN, V.G.",DMK,107709,77.20,GEN,Chennai Metro
51,Poonamallee,5,Krishnaswamy A,DMK,149578,72.99,SC,Chennai Metro

In [14]:
winner2026.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro
16,Ponneri,2,DR.RAVI.M.S,TVK,110439,NaN,SC,Chennai Metro
30,Tiruttani,3,G.HARI,AIADMK,89169,NaN,GEN,Chennai Metro
44,Thiruvallur,4,DR. T. ARUNKUMAR,TVK,92190,NaN,GEN,Chennai Metro
59,Poonamallee,5,PRAKASAM.R,TVK,161309,NaN,SC,Chennai Metro

In [15]:
print(winner2021.shape)
print(winner2026.shape)

(234, 8)
(234, 8)

In [16]:
sorted2021 = df2021.sort_values(['ac_number', 'votes'], ascending=[True, False])
sorted2026 = df2026.sort_values(['ac_number', 'votes'], ascending=[True, False])

In [17]:
top2_2021 = sorted2021.groupby('ac_number').head(2)
top2_2026 = sorted2026.groupby('ac_number').head(2)

In [18]:
margin2021 = top2_2021.groupby('ac_number').agg({
    'votes': lambda x: x.iloc[0] - x.iloc[1]
}).reset_index()

margin2021.columns = ['ac_number', 'margin']

In [19]:
margin2026 = top2_2026.groupby('ac_number').agg({
    'votes': lambda x: x.iloc[0] - x.iloc[1]
}).reset_index()

margin2026.columns = ['ac_number', 'margin']

In [20]:
winner2021 = winner2021.merge(margin2021, on='ac_number')
winner2026 = winner2026.merge(margin2026, on='ac_number')

In [21]:
winner2021[['constituency', 'candidate', 'party', 'votes', 'margin']].head()

   constituency            candidate party   votes  margin
0  Gummidipundi     GOVINDARAJAN T.J   DMK  126452   50938
1       Ponneri  DURAI. CHANDRASEKAR   INC   94528    9689
2     Tiruttani           S.Chandran   DMK  120314   29253
3   Thiruvallur     RAAJENDRAN, V.G.   DMK  107709   22701
4   Poonamallee       Krishnaswamy A   DMK  149578   94110

In [22]:
closest_battles_2026 = winner2026.sort_values('margin').head(10)

closest_battles_2026[['constituency', 'candidate', 'party', 'margin']]

        constituency                candidate   party  margin
184      Tiruppattur  SEENIVASA SETHUPATHY. R     TVK       1
53      Veppanahalli           SRINIVASAN.P.S     DMK     138
228    Kanniyakumari     THALAVAI SUNDARAM. N  AIADMK     214
65             Polur               ABISHEK. R     TVK     227
75      Tirukkoyilur             PALANISAMY S  AIADMK     285
94   Paramathi-Velur                  SEKAR S  AIADMK     308
136       Kulithalai   SURIYANUR. A. CHANDRAN     DMK     579
170       Kumbakonam                   VINOTH     TVK     679
126           Palani         RAVIMANOHARAN. K  AIADMK     693
71        Tindivanam              VANNI ARASU     VCK     734

In [23]:
w21 = winner2021[['ac_number', 'constituency', 'party']]
w26 = winner2026[['ac_number', 'constituency', 'party']]

In [24]:
w21 = w21.rename(columns={'party': 'party_2021'})
w26 = w26.rename(columns={'party': 'party_2026'})

In [25]:
flip_analysis = w21.merge(w26, on=['ac_number', 'constituency'])

In [26]:
flip_analysis['flipped'] = flip_analysis['party_2021'] != flip_analysis['party_2026']

In [27]:
flip_analysis['flipped'].value_counts()

flipped
True     144
False     56
Name: count, dtype: int64

In [28]:
flipped_seats = flip_analysis[flip_analysis['flipped'] == True]

flipped_seats.head(20)

    ac_number       constituency party_2021 party_2026  flipped
0           2            Ponneri        INC        TVK     True
1           3          Tiruttani        DMK     AIADMK     True
2           4        Thiruvallur        DMK        TVK     True
3           5        Poonamallee        DMK        TVK     True
4           6              Avadi        DMK        TVK     True
5           7        Maduravoyal        DMK        TVK     True
6           8           Ambattur        DMK        TVK     True
7           9          Madavaram        DMK        TVK     True
8          10      Thiruvottiyur        DMK        TVK     True
9          12           Perambur        DMK        TVK     True
10         13           Kolathur        DMK        TVK     True
11         14        Villivakkam        DMK        TVK     True
12         15  Thiru-Vi-Ka-Nagar        DMK        TVK     True
13         16             Egmore        DMK        TVK     True
14         17          Royapuram        DMK        TVK     True
17         20    Thousand Lights        DMK        TVK     True
18         21         Anna Nagar        DMK        TVK     True
19         22      Virugampakkam        DMK        TVK     True
20         23           Saidapet        DMK        TVK     True
21         25           Mylapore        DMK        TVK     True

In [29]:
party_flips = flipped_seats.groupby(
    ['party_2021', 'party_2026']
).size().reset_index(name='seats_changed')

party_flips.sort_values('seats_changed', ascending=False)

   party_2021 party_2026  seats_changed
12        DMK        TVK             57
2      AIADMK        TVK             22
7         DMK     AIADMK             22
0      AIADMK        DMK             13
16        INC        TVK              9
11        DMK        PMK              3
17        PMK     AIADMK              2
18        PMK        TVK              2
3      AIADMK        VCK              1
1      AIADMK        INC              1
5         BJP        TVK              1
4         BJP        DMK              1
9         DMK     CPI(M)              1
6      CPI(M)        TVK              1
13        INC        BJP              1
10        DMK       IUML              1
8         DMK       AMMK              1
15        INC        DMK              1
14        INC       DMDK              1
19        VCK     AIADMK              1
20        VCK        DMK              1
21        VCK        TVK              1

In [30]:
winner2021 = winner2021.merge(
    master[['ac_number', 'region']],
    on='ac_number',
    how='left'
)

winner2026 = winner2026.merge(
    master[['ac_number', 'region']],
    on='ac_number',
    how='left'
)

In [32]:
winner2026.columns

Index(['constituency', 'ac_number', 'candidate', 'party', 'votes', 'turnout',
       'reserved', 'region_x', 'margin', 'region_y'],
      dtype='str')

In [33]:
winner2026[['constituency', 'party', 'region_x']].head()

    constituency   party       region_x
0  Gummidipoondi     TVK  Chennai Metro
1        Ponneri     TVK  Chennai Metro
2      Tiruttani  AIADMK  Chennai Metro
3    Thiruvallur     TVK  Chennai Metro
4    Poonamallee     TVK  Chennai Metro

In [37]:
winner2021.columns

Index(['constituency', 'ac_number', 'candidate', 'party', 'votes', 'turnout',
       'reserved', 'region_x', 'margin', 'region_y'],
      dtype='str')

In [39]:
print(winner2021.columns)

Index(['constituency', 'ac_number', 'candidate', 'party', 'votes', 'turnout',
       'reserved', 'region_x', 'margin', 'region_y'],
      dtype='str')

In [40]:
winner2021 = winner2021.drop(columns=['region_y'])
winner2021 = winner2021.rename(columns={'region_x': 'region'})

winner2026 = winner2026.drop(columns=['region_y'])
winner2026 = winner2026.rename(columns={'region_x': 'region'})

In [41]:
winner2021[['constituency', 'party', 'region']].head()

   constituency party         region
0  Gummidipundi   DMK  Chennai Metro
1       Ponneri   INC  Chennai Metro
2     Tiruttani   DMK  Chennai Metro
3   Thiruvallur   DMK  Chennai Metro
4   Poonamallee   DMK  Chennai Metro

In [42]:
region_2021 = winner2021.groupby(
    ['region', 'party']
).size().reset_index(name='seats_2021')

region_2021.head()

    region   party  seats_2021
0  Central  AIADMK          15
1  Central     DMK          21
2  Central     INC           1
3  Central     PMK           3
4  Central     VCK           1

In [43]:
region_2026 = winner2026.groupby(
    ['region', 'party']
).size().reset_index(name='seats_2026')

region_2026.head()

    region   party  seats_2026
0  Central  AIADMK          15
1  Central    DMDK           1
2  Central     DMK           8
3  Central     PMK           3
4  Central     TVK          12

In [44]:
regional_shift = region_2021.merge(
    region_2026,
    on=['region', 'party'],
    how='outer'
).fillna(0)

In [45]:
regional_shift['seat_change'] = (
    regional_shift['seats_2026']
    - regional_shift['seats_2021']
)

In [46]:
regional_shift.sort_values(
    'seat_change',
    ascending=False
).head(20)

           region   party  seats_2021  seats_2026  seat_change
10  Chennai Metro     TVK         0.0        29.0         29.0
38          South     TVK         0.0        26.0         26.0
24          Kongu     TVK         0.0        16.0         16.0
31          North     TVK         0.0        15.0         15.0
5         Central     TVK         0.0        12.0         12.0
18          Delta     TVK         0.0        10.0         10.0
25          North  AIADMK        12.0        15.0          3.0
17          Delta    IUML         0.0         1.0          1.0
29          North    IUML         0.0         1.0          1.0
35          South  CPI(M)         0.0         1.0          1.0
7   Chennai Metro  AIADMK         0.0         1.0          1.0
1         Central    DMDK         0.0         1.0          1.0
6         Central     VCK         1.0         2.0          1.0
12          Delta    AMMK         0.0         1.0          1.0
4         Central     PMK         3.0         3.0          0.0
13          Delta     CPI         1.0         1.0          0.0
11          Delta  AIADMK         4.0         4.0          0.0
0         Central  AIADMK        15.0        15.0          0.0
26          North     CPI         1.0         1.0          0.0
28          North     INC         1.0         0.0         -1.0

In [47]:
winner2021.to_csv("winner2021.csv", index=False)
winner2026.to_csv("winner2026.csv", index=False)

In [48]:
flip_analysis.to_csv("flip_analysis.csv", index=False)

In [49]:
regional_shift.to_csv("regional_shift.csv", index=False)

In [50]:
closest_battles_2026.to_csv("closest_battles_2026.csv", index=False)

In [2]:
import pandas as pd

In [4]:
import pandas as pd

flip_analysis = pd.read_csv("flip_analysis.csv")

flipped_only = flip_analysis[
    flip_analysis['flipped'] == True
]

flipped_only.to_csv("flipped_only.csv", index=False)

print(flipped_only.head())

   ac_number constituency party_2021 party_2026  flipped
0          2      Ponneri        INC        TVK     True
1          3    Tiruttani        DMK     AIADMK     True
2          4  Thiruvallur        DMK        TVK     True
3          5  Poonamallee        DMK        TVK     True
4          6        Avadi        DMK        TVK     True